### ISSUE TITLE
Check for file type or allow option to specify file type

### ISSUE THREAD

**Issue by lukeellison** [vtex/react-upload-csv#16]
If a jpeg or pdf is uploaded it tries to load the whole thing as a csv.

**Comment by isuruamantha** [comment]
Yes. I'm also facing this issue. Any solution or workaround?

**Comment by kcmv** [comment]
@lukeellison  > If a jpeg or pdf is uploaded it tries to load the whole thing as a csv.
@isuruamantha > Yes. I'm also facing this issue. Any solution or workaround?


you can add the accept property to the input `<input type="file" accept=".csv"/>`
