### ISSUE TITLE
Change to generic component

### ISSUE THREAD

**Issue by klzns** [vtex/react-upload-csv#3]
Get inspiration from https://github.com/paypal/downshift to make this component not render a thing, but instead ease the development of UI components that upload a CSV and show a table.

## Expected Behavior
This component should not render UI.

## Current Behavior
Now it's built in the code that renders the UI and it's not possible to change it.

## Possible Solution

```js
<UploadCSV
  headers={['id', 'name', 'email']}
  onUpload={onUpload}>
  {(isUploaded, data}) => {
    {
      isUploaded
      ? (
        <div>
          <table>
            <thead>
              <tr>
                <td>ID</td>
                <td>Name</td>
                <td>E-mail</td>
              </tr>
            </thead>
            <tbody>
              {data.map(line =>
                <tr>
                  <td>{line[0]}</td>
                  <td>{line[1]}</td>
                  <td>{line[2]}</td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      )
    : (
      <div>Upload your .csv file</div>
    )
  })
</UploadCSV>
```
  
## Steps to Reproduce (for bugs)
n/a

## Context
If I try to use this component in another UI it might not suit my needs.

## Your Environment
n/a

**Comment by kevinch** [comment]
Done in https://github.com/vtex/react-csv-parse/pull/5
