### ISSUE TITLE
Handle special characters

### ISSUE THREAD

**Issue by kevinch** [vtex/react-upload-csv#8]
When typing some "special characters" like comma, dot, colon etc. softwares should save the value in the csv file with double quotes:

```
712dd419-3adb-4b3d-9461-8e5e68a09b67,Cancelled,2017-05-26T02:11:51,2017-10-25T12:21:24,,2017-06-17T02:11:51,2017-06-21T02:11:51,"test with comma, then",
5f54e77c226a45eab235cbf540b0ecbf,Cancelled,2017-05-18T07:22:22,2017-10-26T05:11:59,,2017-06-17T07:22:22,2017-06-17T07:22:22,nocomma,
```

This has to be recognized and handled. 
Ex: user can digit a comma within a description field.

**Comment by cickes** [comment]
Also consider the case of a phone number in the first field
`(999) 999-9999`

**Comment by kevinch** [comment]
Done via release `4.0.0`.
